<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Library</OutputType>
    <RootNamespace>UnitTestGpredictConnector</RootNamespace>
    <AssemblyName>UnitTestGpredictConnector</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.*" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SDRSharp.Common">
      <HintPath>..\ext_libs\SDRSharp.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SDRSharp.PanView">
      <HintPath>..\ext_libs\SDRSharp.PanView.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SDRSharp.Radio">
      <HintPath>..\ext_libs\SDRSharp.Radio.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SDRSharp.GpredictConnector\SDRSharp.GpredictConnector.csproj" />
  </ItemGroup>

</Project>