<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Library</OutputType>
    <RootNamespace>SDRSharp.GpredictConnector</RootNamespace>
    <AssemblyName>SDRSharp.GpredictConnector</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SDRSharp.Common">
      <HintPath>..\ext_libs\SDRSharp.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SDRSharp.PanView">
      <HintPath>..\ext_libs\SDRSharp.PanView.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SDRSharp.Radio">
      <HintPath>..\ext_libs\SDRSharp.Radio.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>